x-resources: &limits
  deploy:
    resources:
      limits:
        cpus: 0.5
        memory: 128M

x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"

services:
  web1:
    image: nginx:alpine
    ports:
      - "8081:80"
    <<: [*limits, *logging]
  

  web2:
    image: nginx:alpine
    ports:
      - "8082:80"
    <<: [*limits, *logging]

  web3:
    image: nginx:alpine
    ports:
      - "8083:80"
    <<: [*limits, *logging]
    

